Repository future-standard/scorer-ui-kit, pull requests merged in 2024-12, with the labels that each got.

#526 Bugfix/525 Pagination fix with Label refactor
  packages/storybook/src/stories/Form/Input/RadioButton.stories.tsx
  packages/ui-lib/src/Form/atoms/Label.tsx
  packages/ui-lib/src/Form/atoms/SelectField.tsx
  packages/ui-lib/src/Form/index.ts
  packages/ui-lib/src/Misc/molecules/Pagination.tsx
Labels: bug, Refactor

#527 Fix circular dependency error for FilterButtonDesign type
  packages/ui-lib/src/Filters/FilterTypes.ts
  packages/ui-lib/src/Filters/atoms/FilterButton.tsx
  packages/ui-lib/src/Filters/atoms/FilterDropHandler.tsx
  packages/ui-lib/src/Filters/atoms/ToggleButton.tsx
  packages/ui-lib/src/Filters/index.ts
  packages/ui-lib/src/Filters/molecules/FilterDropdown.tsx
  packages/ui-lib/src/Filters/molecules/SortDropdown.tsx
Labels: bug

#524 Datepicker Dot Markers
  packages/storybook/src/stories/Filters/molecules/DatePicker.stories.tsx
  packages/storybook/src/stories/Filters/organisms/FilterBar.stories.tsx
  packages/storybook/src/stories/helpers/datePicker_sample.ts
  packages/ui-lib/src/Filters/molecules/DatePicker.tsx
  packages/ui-lib/src/Filters/molecules/DropdownDatePicker.tsx
Labels: Feature Iteration

#529 Bump for release v2.7.0
  package-lock.json
  package.json
  packages/ui-lib/package.json
Labels: Release
