Repository future-standard/scorer-ui-kit, pull requests merged in 2024-10, with the labels that each got.

#467 Tooltip feature
  packages/example/src/components/StatusComponent.tsx
  packages/example/src/pages/TablePage.tsx
  packages/storybook/src/stories/Alerts/Tooltip.stories.tsx
  packages/ui-lib/src/Alerts/atom/Tooltip.tsx
  packages/ui-lib/src/Alerts/index.ts
  packages/ui-lib/src/index.tsx
  packages/ui-lib/src/theme/ThemeVariables.ts
  packages/ui-lib/src/theme/variables/Colors.ts
Labels: New Feature

#484 Bump for release v2.3
  package-lock.json
  package.json
  packages/ui-lib/package.json
Labels: Release

#485 Bump for release v2.4
  package-lock.json
  package.json
  packages/ui-lib/package.json
Labels: Release

#489 Revert fix-package-lock.json bad update when trying Sass with layouts
  package-lock.json
Labels: bug

#494 Bump for release v2.5.0
  package-lock.json
  package.json
  packages/ui-lib/package.json
Labels: Release

#495 Pagination activePage prop not updating value
  packages/storybook/src/stories/Misc/molecules/Pagination.stories.tsx
  packages/ui-lib/src/Misc/molecules/Pagination.tsx
Labels: bug

#501 Bump for release v2.6.0
  package-lock.json
  package.json
  packages/ui-lib/package.json
Labels: Release

#500 Fixes: Checkbox, Radio and FilterButton color fixes
  packages/ui-lib/src/Filters/atoms/FilterButton.tsx
  packages/ui-lib/src/Filters/atoms/FilterDropdownContainer.tsx
  packages/ui-lib/src/Form/atoms/Checkbox.tsx
  packages/ui-lib/src/Form/atoms/FilterOption.tsx
  packages/ui-lib/src/Form/atoms/RadioButton.tsx
  packages/ui-lib/src/theme/variables/Colors.ts
Labels: bug

#503 Add disableCheckbox option to rows
  packages/storybook/src/stories/Tables/molecules/LoadingTable.stories.tsx
  packages/ui-lib/src/Tables/atoms/TypeTableRow.tsx
  packages/ui-lib/src/Tables/index.ts
  packages/ui-lib/src/Tables/molecules/TypeTableHeader.tsx
  packages/ui-lib/src/Tables/organisms/TypeTable.tsx
Labels: Enhancement

#504 Hotfix: Main Menu - Sub Menus wrong height if contents was changed after initialisation
  packages/ui-lib/src/Global/atoms/NavigationItem.tsx
Labels: bug, High Priority

#505 Submenu height fix.
  packages/ui-lib/src/Global/atoms/NavigationItem.tsx
  packages/ui-lib/src/Global/organisms/MainMenu.tsx
  packages/ui-lib/src/Global/organisms/MobileMenu.tsx
Labels: bug

#507 Bump for release v2.6.3
  package-lock.json
  package.json
  packages/ui-lib/package.json
Labels: Release
